server:
  port: 8080

spring:
  application:
    name: neogroup.demo

  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
        show_sql: false

  datasource:
    url: jdbc:postgresql://localhost:5432/neogroup-demo
    username: &db_username neogroup-demo
    password: &db_password neogroup-demo
    hikari:
      connection-timeout: 5000

  liquibase:
    enabled: true
    change-log: classpath:db/changelog/main-changelog.xml
    user: *db_username
    password: *db_password

  quartz:
    job-store-type: memory

logging:
  level:
    xyz.sanvew: DEBUG

log:
  enabled: true
  flush:
    retry-delay: 5000
    retry-count: 5
    cron: "0/10 * * ? * *"
  log:
    cron: "*/1 * * ? * *"
